---
theme: null
title: 
first_name: Michaela
last_name: Philip

# Site Author
author:
  name             : "Michaela Philip"
  avatar           : "avatar.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : >-

  location         : "Atlanta, GA"
  email            :

# Site Footer
# footer:
#   links:
#     - label: "Email"
#       icon: "fas fa-fw fa-envelope-square"
#       url: "mailto:mphili6@emory.edu"
#     - label: "Twitter"
#       icon: "fab fa-fw fa-square-x-twitter"
#       url: "https://twitter.com/MichaelaPhilip"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/michaela-philip"

# Site Footer
# footer:
#   links:
#     - label: "Twitter"
#       icon: "fab fa-fw fa-square-x-twitter"
#       url: "https://twitter.com/gerkElznik"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/gerkElznik"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-archives
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-assets
  - jekyll-optional-front-matter
---